id: IF1C90C1C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:17:22+00:00'
last_modified: '2022-06-07T15:23:15.204956+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22393
  title: གསུང་འབུམ། སྒམ་པོ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1B54:
      image_group_id: I01JW305
      title: ''
      total_pages: 816
      order: 1
      base_file: 1B54.txt
    4B69:
      image_group_id: I01JW306
      title: ''
      total_pages: 644
      order: 2
      base_file: 4B69.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
